# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Digimpactsss(object):
    def setupUi(self, Digimpactsss):
        Digimpactsss.setObjectName("Digimpactsss")
        Digimpactsss.resize(400, 300)
        self.tableWidget = QtWidgets.QTableWidget(Digimpactsss)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 381, 281))
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)

        self.retranslateUi(Digimpactsss)
        QtCore.QMetaObject.connectSlotsByName(Digimpactsss)

    def retranslateUi(self, Digimpactsss):
        _translate = QtCore.QCoreApplication.translate
        Digimpactsss.setWindowTitle(_translate("Digimpactsss", "Dialog"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Digimpactsss", "Project"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Digimpactsss", "Distance"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Digimpactsss", "Type"))
